name: ci

on:
  push:
    paths-ignore:
    - 'doc/**'
    - 'img/**'
    - 'changelog.md'
    - 'readme.md'
  pull_request:

jobs:
  build:
    permissions:
      id-token: write
      actions: write
      contents: write
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: NuGet Login
        uses: NuGet/login@v1
        id: nuget-login
        with:
          user: xoofx
      - name: "Build, Test, Pack and Publish"
        uses: xoofx/.github/.github/actions/dotnet-releaser-action@main
        with:
          NUGET_TOKEN: ${{ steps.nuget-login.outputs.NUGET_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
